title: Marco Gabrielli
description: Webiste of Marco Gabrielli 
theme: just-the-docs

url: https://mgabriell1.github.io/

aux_links: # remove if you don't want this link to appear on your pages
  Template Repository: https://mgabriell1.github.io/


