title: Personal website of Marco Gabrielli
description: Personal website of Marco Gabrielli
theme: just-the-docs

url: https://mgabriell1.github.io/

#aux_links:
#  Template Repository: https://github.com/just-the-docs/just-the-docs-template





